// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: {
          /** any - use sql.*() */
          vendedor: SQLTypeMarker;
        };
        result: Array<{
          /** Nome do vendedor responsavel pelo cliente. */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          viraram_pedido: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** any - use sql.*() */
          vendedor: SQLTypeMarker;
        };
        result: Array<{
          /** Identificador do cliente. */
          cliente_id: string;
          /** Posicao do cliente na fila do vendedor (1 = prioridade maxima). */
          ordem: number;
          /** Nome fantasia / razao social do cliente. */
          razao_social: string;
          /** @sqlType STRING */
          localizacao: string;
          /** Ticket medio do cliente (receita / frequencia). */
          ticket_medio: number;
          /** Nome do vendedor responsavel pelo cliente. */
          vendedor: string;
          /** @sqlType DOUBLE */
          chance_pct: number;
          /** Faixa do score: Fria, Morna, Quente ou Muito quente. */
          faixa: string;
          /** Frase em portugues explicando por que este cliente esta na fila. */
          motivo: string;
          /** SKU sugerido para oferta: marca preferida que o cliente parou de comprar, com saldo do estoque. */
          sugestao: string;
          /** Resultado da ligacao: vendeu | vai_pensar | sem_interesse | nao_atendeu. */
          status_retorno: string;
          /** Texto livre do vendedor. Campo opcional para contexto adicional. */
          comentario_retorno: string;
          /** Timestamp UTC em que o registro foi feito. Use MAX para pegar o mais recente por cliente. */
          quando_retorno: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: {
          /** any - use sql.*() */
          vendedor: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType INT */
          acertos_top200: number;
          /** @sqlType DOUBLE */
          lift: number;
          /** @sqlType DOUBLE */
          taxa_base_pct: number;
          /** @sqlType DECIMAL(16,1) */
          conversao_prevista_pct: number;
          /** @sqlType BIGINT */
          ja_trabalhados: number;
          /** @sqlType BIGINT */
          viraram_pedido: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          value: string;
          /** @sqlType STRING */
          label: string;
        }>;
      };
  }
}
